### PR TITLE
Added matic mumbai testnet config and deployed contracts on matic mumbai testnet

### PR DESCRIPTION
**Pull request by adi44**

### CODE REVIEW

**Review by dev1644 — COMMENTED** [review]
Hi @adi44 , why `addresses & abis` of contracts deployed at `goerli` network are removed?

**Comment by adi44** [comment]
> Hi @adi44 , why `addresses & abis` of contracts deployed at `goerli` network are removed?
I will check, When I deployed, the goerli folder got replaced by matic folder

**Comment by hrishikeshio** [comment]
Is it configured to deploy on Matic mainnet or testnet? which testnet? Please mention explicitly in configuration and PR.

**Comment by adi44** [comment]
> Is it configured to deploy on Matic mainnet or testnet? which testnet? Please mention explicitly in configuration and PR.

it is configured to deploy on Matic Mumbai testnet. I will change the PR name and put comments in the config file

**Comment by adi44** [comment]
> Hi @adi44 , why `addresses & abis` of contracts deployed at `goerli` network are removed?

I have redeployed contracts on goerli and pushed it on this branch.

**Comment by SkandaBhat** [comment]
@adi44 please add a description to this PR with the intent and purpose. Also please create an issue for this PR and link it here.

**Comment by SkandaBhat** [comment]
Closing this as we need to spec this out first.

**Pull request closed without merging**
