### PR TITLE
resolved-todo for Parameters.sol

### LINKED ISSUE #172: Analyze what can be the maximum value (if needs to be reset) of these params.
Currently, we have set the value of the parameter, but we haven't decided on what could be the maximum value for every constant. for which we need to do some analysis.

### PR DESCRIPTION
**Pull request by adi44**
there was a to-do comment on Parameters. sol to decide the Maximum Value of all the constants. But as per discussion, we do not need to have maximum values for constants. So I have removed that todo comment from Parameters.sol
fixes #172

### CODE REVIEW

**Comment by SkandaBhat** [comment]
@adi44 This needs more description.

**Comment by adi44** [comment]
> @adi44 This needs more description.

@SkandaBhat I have added description

**Comment by abhishekvispute** [comment]
Hey,
I think it would be better if we remove all todos in one single PR, rather than having PR for each.
We will remove all of these todos once we resolve all of them, at once.
IMO It will be better for tracking.

What do you think ? @SkandaBhat  @adi44

**Comment by adi44** [comment]
> Hey @adi44,
> Is there any other to-do which we have already taken care of, or which is not needed anymore like this?
> I think it would be better if we have one PR removing all of the dormant to-do at once, rather than having a single for each.
> What do you think?

@abhishekvispute Hey! yeah, I think there is one more TODO which is not needed any more. Yeah, I think it would be better to have it in one PR and link the issue.

**Pull request closed without merging**
