### PR TITLE
Made Slashing Penalty a Governance Parameter

### LINKED ISSUE #152: Make Slashing penalty as a governance parameter
**Describe the bug**
As of now slashing penalty is hardcoded, we need to make it a gov parameter and reduce it,
as directly slashing to 0 is too strict.

### PR DESCRIPTION
**Pull request by GauravJain9**
Fixes #152
Added a gov param as "percentSlashPenalty" by which we can decide and update how much percentage of the staker should be slashed and updated the slash function accordingly.

### CODE REVIEW

**Comment by GauravJain9** [comment]
@abhishekvispute it's working actually signers[19] didn't had funds so transferred it now shall I keep the tokenamount passed as inintial weights in test case manually or shall I pass it by taking value from VoteManager like for eg. "[tokenAmount('420000'), tokenAmount('18000')] // initial weights" to "[await voteManager.getVoteWeight(epoch, 1, sortedVotes[0])] // initial weights" .

**Comment by abhishekvispute** [comment]
Hey @GauravJain9 
How it was working before in this case then if signers[19] never had those funds?

On keeping it manually or from contract 
First check if the calculated value in your test manyal one is equal to what we get from contract
Then in next test it we can pass any of them

**Comment by GauravJain9** [comment]
Hey @abhishekvispute 
Previously it working because in test case of finalize dispute signers[19] got slashpenalty/2 as reward by slashing signers[5] and the amount signers[19] received was i think tokenAmount('210000') which is far greater than what signers[19] is staking in the below test cases which is tokenAmount('19000') so that's why it was working then.

On keeping it manually or from contract
I have checked in every places by manually and from contract in both the cases same values are being calculated so we can pass any of them either in all or in selected test cases as per requirement. So as of now I haven't changed I have kept it manually again since the issue is resolved and it actually had nothing to do with this.

**Review by abhishekvispute — APPROVED** [review]
LGTM

**Review by SkandaBhat — APPROVED** [review]

**Pull request merged**
