### PR TITLE
Scenario tests

### LINKED ISSUE #455: 100 epochs of constant voting and participation

### LINKED ISSUE #456: Staker is initially active and then becomes inactive more than the GRACE PERIOD

### PR DESCRIPTION
**Pull request by SamAg19**
Fixes #455 
Fixes #456  
Template for scenario based testing created plus 2 test scenarios have been written

### CODE REVIEW

**Comment by SkandaBhat** [comment]
Please describe which scenario has been tested here in a comment

**Comment by shekhar2807** [comment]
Scenarios tested :

- 100 epochs of constant voting and participation.
- Staker is initially active and then becomes inactive more than the GRACE PERIOD.

**Review by SkandaBhat — CHANGES_REQUESTED** [review]
Move the scenarios to separate files under `scenarios` folder.

**Comment by SkandaBhat** [comment]
Closing this. @SamAg19 please add the scenarios to this branch.

**Pull request closed without merging**
