### PR TITLE
Check Epoch removed

### LINKED ISSUE #589: Remove epoch check for all except commit, reveal, propose

### PR DESCRIPTION
**Pull request by SamAg19**
fixes #589

### CODE REVIEW

**Comment by hrishikeshio** [comment]
Please note that the issue has tag "analysis"

Please provide reasons why its safe to remove the epoch restriction for each of these functions.

**Comment by SamAg19** [comment]
Epoch restriction can be removed in withdraw function only as the razors that are going to be withdrawn have already been locked and separated from the network at the time of unstake. A withholding attack will not cause any loss to the locked funds.

Will reinstate the epoch restriction in other functions except withdraw.

**Comment by hrishikeshio** [comment]
> Epoch restriction can be removed in withdraw function only as the razors that are going to be withdrawn have already been locked and separated from the network at the time of unstake. A withholding attack will not cause any loss to the locked funds.
> 
> Will reinstate the epoch restriction in other functions except withdraw.

why cant we remove epoch check in other functions?

**Comment by SkandaBhat** [comment]
Delegate and unstake should not have epoch check. @SamAg19 please make the changes accordingly.

**Review by SkandaBhat — CHANGES_REQUESTED** [review]
Please make the required changes.

**Review by hrishikeshio — APPROVED** [review]

**Review by abhishekvispute — APPROVED** [review]

**Pull request merged**
