### PR TITLE
Applicable functions made internal

### LINKED ISSUE #529: Sweep through contracts and make functions in internal if possible
For example: isElectedProposer in blockManager

_Originally posted by @abhishekvispute in https://github.com/razor-network/contracts/pull/527#discussion_r737308779_

### PR DESCRIPTION
**Pull request by abhishekvispute**
fixes #529 

image

https://blog.polymath.network/solidity-tips-and-tricks-to-save-gas-and-reduce-bytecode-size-c44580b218e6

### CODE REVIEW

**Comment by abhishekvispute** [comment]
Here though theory suggests it should go down, gasBot is saying diff 
Checking that

**Comment by abhishekvispute** [comment]
This is weird 
If we make getEpoch and getState public commit goes back to 408911
with internal its up to 409320, as above

**Comment by abhishekvispute** [comment]
GasBot compares max, if we compare avg then also this pr adds :|

This Branch
 VoteManager        ·  commit                            ·     110272  ·     409320  ·        175795  ·           78  ·      84.85  
 
Master
 VoteManager        ·  commit                            ·     110227  ·     408911  ·        175633  ·           78  ·      85.64

**Review by SkandaBhat — APPROVED** [review]
LGTM

**Review by SamAg19 — APPROVED** [review]

**Pull request merged**
