### PR TITLE
Fixed the gas Amount for Givesorted function

### PR DESCRIPTION
**Pull request by adi44**
the total amount of gas consumed by the give sorted function is around 190k out of which 60k is needed for last two assignments.
Fixes https://github.com/razor-network/contracts/issues/177

### CODE REVIEW

**Comment by SkandaBhat** [comment]
Could you please add more info on how 60k was arrived at?

**Comment by adi44** [comment]
> Could you please add more info on how 60k was arrived at?

the amount of gas consumed by whole function is approximately 190k. And the gas cosumed by function without last two assignment statements is 130k. the difference of that is the amount gas consumed by last two lines.

**Comment by SkandaBhat** [comment]
Can you please add accurate numbers?

**Comment by adi44** [comment]
> Can you please add accurate numbers?
total gas consumed : 190167
gas consumed while last two lines were commented : 145105

**Comment by adi44** [comment]
> Can you please add accurate numbers?

total gas consumed : 190167
gas consumed while last two lines were commented : 145105

**Review by SkandaBhat — APPROVED** [review]

**Comment by hrishikeshio** [comment]
> > Can you please add accurate numbers?
> 
> total gas consumed : 190167(maximum Cap)
> gas consumed while last two lines were commented : 145105 (maximum Cap)



> > Could you please add more info on how 60k was arrived at?
> 
> the amount of gas consumed by whole function is approximately 190k. And the gas cosumed by function without last two assignment statements is 130k. the difference of that is the amount gas consumed by last two lines.


not sure if that's the best method to estimate. You can use console.log(gasleft() ) before and after those two lines and paste the log here.

**Comment by adi44** [comment]
> > > Can you please add accurate numbers?
> > 
> > 
> > total gas consumed : 190167(maximum Cap)
> > gas consumed while last two lines were commented : 145105 (maximum Cap)
> 
> > > Could you please add more info on how 60k was arrived at?
> > 
> > 
> > the amount of gas consumed by whole function is approximately 190k. And the gas cosumed by function without last two assignment statements is 130k. the difference of that is the amount gas consumed by last two lines.
> 
> not sure if that's the best method to estimate. You can use console.log(gasleft() ) before and after those two lines and paste the log here.

Screenshot from 2021-07-23 16-56-41

**Comment by adi44** [comment]
> > > > Can you please add accurate numbers?
> > > 
> > > 
> > > total gas consumed : 190167(maximum Cap)
> > > gas consumed while last two lines were commented : 145105 (maximum Cap)
> > 
> > 
> > > > Could you please add more info on how 60k was arrived at?
> > > 
> > > 
> > > the amount of gas consumed by whole function is approximately 190k. And the gas cosumed by function without last two assignment statements is 130k. the difference of that is the amount gas consumed by last two lines.
> > 
> > 
> > not sure if that's the best method to estimate. You can use console.log(gasleft() ) before and after those two lines and paste the log here.
> 
> Screenshot from 2021-07-23 16-56-41
> @hrishikeshio there is huge difference in what I estimated using hardhat gas reporter and console.log

Screenshot from 2021-07-23 17-13-05
if we take according to minimum then that comes approximately similar to what calaculation was done using console.log. but with maximum cap it differs a lot. which one should I consider

**Comment by SkandaBhat** [comment]
Let's go ahead with max. console log will show gas left wrt current execution. cc: @hrishikeshio

**Comment by abhishekvispute** [comment]
Hey @adi44 
Actually, I am not sure on the reason behind this if
so there is 
````
for
{
xxxxxxxx

if(gasLeft)
}  

those two lines 
````
As per my assumption, we had this if(gasLeft) to check if 
executing 
```
xxxxxxx
```
is possible for not for i'th iteration

if its possible go ahead, if not it breaks, and the staker can again call giveSorted from that breakpoint as we allow dispute in batches
If we didn't have this condition at all
What would have happened is tx would have reverted 
and staker had to call giveSorted from 1 to n again.

With this, if gas req is less you can start from breakpoint.

So if this is correct 
IMO we should calculate gas consumption of
```
xxxxxxxx
```
Not those two lines

 CC : @hrishikeshio @SamAg19 @SkandaBhat

**Comment by hrishikeshio** [comment]
> Hey @adi44
> Actually, I am not sure on the reason behind this if(gasLeft)
> so there is
> 
> ```
> for
> {
> xxxxxxxx
> 
> if(gasLeft)
> }  
> 
> those two lines 
> ```
> 
> My guess is, we had this if(gasLeft) to check if
> executing
> 
> ```
> xxxxxxx
> ```
> 
> is possible or not for i'th iteration
> 
> if its possible go ahead,
> if not it breaks, and the staker can again call giveSorted from that breakpoint as we allow dispute in batches
> 
> If we didn't have this condition at all
> What would have happened is tx would have reverted
> and staker would have to call giveSorted from 1 to n again.
> 
> With this, if gasLeft is less you can start from breakpoint.
> 
> So if this is correct
> IMO we should calculate gas consumption of
> 
> ```
> xxxxxxxx
> ```
> 
> Not of those two lines
> Also, I am not able to think of any reason for calculating gas req for those 2 lines, if there is, please let me know.
> 
> @hrishikeshio, @SamAg19, @SkandaBhat Please correct me if I am wrong

you are right.

also after influence, the gas required for this loop will be much less.
after influence is merged, check gas required for the loop.

**Comment by SkandaBhat** [comment]
Closing this and putting the issue on hold.

@hrishikeshio @abhishekvispute @adi44

**Pull request closed without merging**
